name: Build Windows App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build and Package (Windows)
        run: npm run pack:win
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timer-windows
          path: release/**
          if-no-files-found: error
